### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IvnSkr** [shahradelahi/wireadmin#1]
So this admin panel is it possible to connect multiple vpn servers so basically 2 vps servers that i configured as a vpn?

**Comment by shahradelahi** [comment]
This allows you to run multiple instances of WireGuard on different ports on the same server. One special thing about this is that you can send your traffic through the Tor network.

Currently, I am focusing on making the app more lightweight and stable. In the future, I may add a feature for managing remote servers.
