### ISSUE TITLE
No Login possible

### ISSUE THREAD

**Issue by erwiower2** [shahradelahi/wireadmin#2]
Hi, I have tested some versions: I can start the docker and access the login page, but I cannot click the login button. In console log I see: Server-Validation failure.

Ich stopped, deleted and reinstalled the container multiple times - no difference.

A few months ago I have tested and it worked. What can I go? Thanks in advance for your reply.

**Comment by shahradelahi** [comment]
I just tested the latest version and mostly there wasn't anything wrong with it. If you don't mind, please use the following command to retrieve the server logs:

```sh
docker ps -a | grep '<nameOfContainer>$'
docker logs <nameOfContainer>
```

It might be a large chunk of logs, but please try to send only the errors that you think are related.

Also, make sure your browser accepts cookies.

**Comment by shahradelahi** [comment]
Try the new canary release.

```sh
docker pull litehex/wireadmin:canary-479c4093fcccda44f460317a5d4f13b7377da045
# Or
docker pull ghcr.io/shahradelahi/wireadmin:canary-479c4093fcccda44f460317a5d4f13b7377da045
```

If you are still able to reproduce the issue, please share the error logs.

**Comment by erwiower2** [comment]
Hi Dear,

thanks for your quick reply.

Nothing of those works. I think it’s a problem of my server, because I get in browser console error code 403 forbidden. Don’t know why.
Nftables and iptables is disabled.

As you can see:




Kind regards.

**Comment by erwiower2** [comment]
It’s the same problem in UTM Virtual Linux machine:

**Comment by shahradelahi** [comment]
Please provide steps to reproduce the issue.

**Comment by xiao-Long-Long** [comment]
“traints will exist for the form. Set the warnings.noValidationAndConstraints option to false to disable this warning.”
**The server interface outputs this error.**
To disable the warning for form validation and constraints, you can set the warnings.noValidationAndConstraints option to false. This would suppress the warning about the existence of constraints for the form.

If this problem needs to be dealt with, you can log in. Because I also encountered this problem.

**Comment by erwiower2** [comment]
Hi thanks for your message.

How can I disable this?

**Comment by koloner** [comment]
http://ip:3000/login

403 Forbidden

{"message":"Cross-site POST form submissions are forbidden"}

the is response when try to login to admin panel

**Comment by shahradelahi** [comment]
Hello @erwiower2 and @koloner,

Please try this canary version. I have fixed a few minor bugs in it:

```bash
docker pull ghcr.io/shahradelahi/wireadmin:2.0.0-canary.0
```

For now, I am closing this issue as resolved. If you experience any issues with the app, please open another issue and provide steps to reproduce.
